# Generated by Django 3.2.5 on 2022-03-04 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs_app', '0004_delete_company'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='profile_pic',
        ),
        migrations.AddField(
            model_name='application',
            name='Education_last',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='achievements',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='skills',
            field=models.TextField(blank=True, null=True),
        ),
    ]
